version: "3.3"

services:
    db:
        container_name: processor-db
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: processor
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - './docker/db/sql:/docker-entrypoint-initdb.d'
        networks: 
            network_api:
                ipv4_address: 10.0.0.2

    processor:
        tty: true
        container_name: processor-processor
        build:
            context: ./docker/processor
        volumes:
            - ".:/processor"
        depends_on:
            - db
        networks: 
            network_api:
                ipv4_address: 10.0.0.3

networks:
    network_api:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16