version: "3.3"

services:
    db:
        container_name: processor-db
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: processor
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - './docker/db/sql:/docker-entrypoint-initdb.d'
        networks: 
            - network_api

    processor:
        tty: true
        container_name: processor-processor
        build:
            context: ./docker/processor
        volumes:
            - "./src:/processor"
        depends_on:
            - db